name: '${mod_name}'
version: '${version}'
author: '${authors}'
description: '${description}'
website: '${homepage_url}'
main: '${group}.platforms.BukkitPlugin'
depend: [ TaterLib ]
depends: [ TaterLib ]
softdepend: [ ]
softdepends: [ ]
folia-supported: true
