modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "${issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "${update_json_url}"
displayURL = "${homepage_url}"
logoFile = "${mod_name}.png"
credits = "${authors}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''

[[mods]]
modId = "tater_modlib_base"
version = "${modlib_version}"
displayName = "Muxins"
displayTest = "IGNORE_SERVER_VERSION"

[[mods]]
modId = "crossperms"
version = "${modlib_version}"
displayName = "CrossPerms"
displayTest = "IGNORE_SERVER_VERSION"

[[mods]]
modId = "tater_metadata"
version = "${modlib_version}"
displayName = "TaterMetadata"
displayTest = "IGNORE_SERVER_VERSION"

[[mods]]
modId = "muxins"
version = "${modlib_version}"
displayName = "Muxins"
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "${mod_id}.mixins.json"

# Forge Dependency
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = false
type = "optional"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# NeoForge Dependency
[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = false
type = "optional"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# LuckPerms
[[dependencies.${mod_id}]]
modId = "luckperms"
mandatory = false
type = "optional"
versionRange = "[${luckperms_version},)"
ordering = "NONE"
side = "SERVER"
