name: '${mod_name}'
version: '${version}'
author: '${authors}'
description: '${description}'
website: '${homepage_url}'
main: 'dev.neuralnexus.taterloader.platforms.BukkitLoaderPlugin'
depend: [ ]
depends: [ ]
softdepend: [ LuckPerms, PermissionsEx, Vault ]
softdepends: [ LuckPerms, PermissionsEx, Vault ]
folia-supported: true
