modLoader = "javafml
loaderVersion = "[,)"
license = "${license}"
issueTrackerURL = "${issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "${update_json_url}"
displayURL = "${homepage_url}"
logoFile = "${mod_name}.png"
credits = "${authors}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''

# NeoForge Dependency
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "[,)"
ordering = "NONE"
side = "BOTH"

# LuckPerms
[[dependencies.${mod_id}]]
modId = "luckperms"
type = "optional"
versionRange = "[${luckperms_version},)"
ordering = "NONE"
side = "SERVER"
