modLoader = "javafml
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "${issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage_url}"
logoFile = "${mod_name}.png"
credits = "${authors}"
authors = "${authors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${description}'''

#[[mixins]]
#config = "${mod_id}.mixins.json"

# Forge Dependency
[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = false
type = "optional"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# NeoForge Dependency
[[dependencies.${ mod_id }]]
modId = "neoforge"
mandatory = false
type = "optional"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# TaterLib Dependency
[[dependencies.${ mod_id }]]
modId = "taterlib"
mandatory = true
type = "required"
versionRange = "[${taterlib_version},)"
ordering = "BEFORE"
side = "BOTH"
